// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mes_server.Data;

#nullable disable

namespace mes_server.Migrations
{
    [DbContext(typeof(MESDbContext))]
    partial class MESDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mes_server.Models.History.Performance", b =>
                {
                    b.Property<int>("PerfID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfID"));

                    b.Property<int>("BadQty")
                        .HasColumnType("int");

                    b.Property<int>("GoodQty")
                        .HasColumnType("int");

                    b.Property<int>("InputQty")
                        .HasColumnType("int");

                    b.Property<string>("LotID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<int>("ReasonCode")
                        .HasColumnType("int");

                    b.Property<string>("ToolID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderID")
                        .HasColumnType("int");

                    b.HasKey("PerfID");

                    b.HasIndex("LotID");

                    b.HasIndex("ProcessID");

                    b.HasIndex("ReasonCode");

                    b.HasIndex("ToolID");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkOrderID");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("mes_server.Models.History.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentID"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderID")
                        .HasColumnType("int");

                    b.HasKey("ShipmentID");

                    b.HasIndex("ProductID");

                    b.HasIndex("WorkOrderID");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("mes_server.Models.History.ToolHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<int>("BeforeCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reson")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ToolID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HistoryID");

                    b.HasIndex("ToolID");

                    b.ToTable("ToolHistories");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.BOM", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProcessID")
                        .HasColumnType("int");

                    b.Property<int>("RequiredQty")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "MaterialID", "ProcessID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("ProcessID");

                    b.ToTable("BOMs");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.BadReasonMaster", b =>
                {
                    b.Property<int>("ReasonCode")
                        .HasColumnType("int");

                    b.Property<string>("ReasonDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReasonCode");

                    b.ToTable("BadReasonMasters");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.ProcessMaster", b =>
                {
                    b.Property<int>("ProcessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessID"));

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.HasKey("ProcessID");

                    b.ToTable("ProcessMasters");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.ProductMaster", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("ProductMasters");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.RawMaterial", b =>
                {
                    b.Property<string>("MaterialID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SafetyStock")
                        .HasColumnType("int");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.HasKey("MaterialID");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mes_server.Models.Production.Lot", b =>
                {
                    b.Property<string>("LotID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CurrentProcessID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalBadQty")
                        .HasColumnType("int");

                    b.HasKey("LotID");

                    b.HasIndex("CurrentProcessID");

                    b.HasIndex("OrderID");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("mes_server.Models.Production.Tool", b =>
                {
                    b.Property<string>("ToolID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ToolID");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("mes_server.Models.Production.WorkOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalBadQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalGoodQty")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("mes_server.Models.History.Performance", b =>
                {
                    b.HasOne("mes_server.Models.Production.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.MasterData.ProcessMaster", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.MasterData.BadReasonMaster", "BadReason")
                        .WithMany()
                        .HasForeignKey("ReasonCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.Production.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.MasterData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.Production.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BadReason");

                    b.Navigation("Lot");

                    b.Navigation("Process");

                    b.Navigation("Tool");

                    b.Navigation("User");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("mes_server.Models.History.Shipment", b =>
                {
                    b.HasOne("mes_server.Models.MasterData.ProductMaster", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.Production.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("mes_server.Models.History.ToolHistory", b =>
                {
                    b.HasOne("mes_server.Models.Production.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.BOM", b =>
                {
                    b.HasOne("mes_server.Models.MasterData.RawMaterial", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.MasterData.ProcessMaster", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mes_server.Models.MasterData.ProductMaster", "Product")
                        .WithMany("BOMs")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Process");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("mes_server.Models.Production.Lot", b =>
                {
                    b.HasOne("mes_server.Models.MasterData.ProcessMaster", "CurrentProcess")
                        .WithMany()
                        .HasForeignKey("CurrentProcessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mes_server.Models.Production.WorkOrder", "WorkOrder")
                        .WithMany("Lots")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentProcess");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("mes_server.Models.Production.WorkOrder", b =>
                {
                    b.HasOne("mes_server.Models.MasterData.ProductMaster", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("mes_server.Models.MasterData.ProductMaster", b =>
                {
                    b.Navigation("BOMs");
                });

            modelBuilder.Entity("mes_server.Models.Production.WorkOrder", b =>
                {
                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
